/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "primeChk.h"

int *
primeness_1_svc(prime_t *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
    printf("%s\n", "Prime checker function called.");
    printf("Evaluating primeness for #%d\n", argp->checkPrime);

    argp->isPrime = check_Primeness(argp);

    if(argp->isPrime){ 
        printf("#%d is Prime?: TRUE\n", argp->checkPrime);
    } else {
        printf("#%d is Prime?: FALSE\n", argp->checkPrime);
    }

	return &result;
}

bool check_Primeness(prime_t p) {
    return true;
}
